# Numpy
# Pandas Matplot
    - inferential Analysis
    - Descriptive
    - EDA (Exploratory Data Analysis)
    - Machine Learning (SKL)
    
# Deep Learning

## Numpy
    - Numerical Python
    - Array
    - Fastest
    - Vectorised Operation
    - Contingeous Memory
    

In [2]:
import numpy as np

### 1. Create a NumPy array of shape (3, 4) with random integer values.

In [7]:
arr2d = np.array(1)
print(arr2d)

1


In [8]:
import numpy as np

# Create a 3x4 array with random integer values between 0 and 9
arr_task1 = np.random.randint(0, 10, size=(3, 4))

print("Task 1:")
print(arr_task1)


Task 1:
[[7 0 7 0]
 [0 8 0 6]
 [4 2 4 0]]


In [9]:
arr_task1 = np.random.randint(0, 10, size=(3, 4))

print("Task 1:")
print(arr_task1)


Task 1:
[[5 2 3 1]
 [9 0 7 9]
 [6 0 0 3]]
