# Numpy
# Pandas Matplot
    - inferential Analysis
    - Descriptive
    - EDA (Exploratory Data Analysis)
    - Machine Learning (SKL)
    
# Deep Learning

## Numpy
    - Numerical Python
    - Array
    - Fastest
    - Vectorised Operation
    - Contingeous Memory
    

In [2]:
import numpy as np

### Creating 1D array using a Python List

In [3]:
x = np.array([22,33,44,55])
x

array([22, 33, 44, 55])

In [4]:
x.size

4

In [5]:
# 1D Array is vector, and vector don't have the rows and columns rather it has elements
# 2D Array is Matrix,
# 3D Array is Cube,
# nD Array is ............

x.shape

(4,)

In [6]:
x.ndim

1

### Creating 1D array using range() function

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(arr1d.size)
print(arr1d.shape)
print(arr1d.ndim)

10
(10,)
1


### Creating 2D array using a Python List

In [9]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [10]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

12
(4, 3)
2


In [11]:
arr2d = np.arange(20).reshape(1,20)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [12]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(1, 20)
2


In [13]:
arr2d = np.arange(20).reshape(20,1)
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [14]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(20, 1)
2


In [15]:
arr2d = np.arange(20).reshape(10,2)
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [16]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(10, 2)
2


In [17]:
arr2d = np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(5, 4)
2


In [19]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(4, 5)
2


In [21]:
arr2d = np.arange(20).reshape(2,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
print(arr2d.size)
print(arr2d.shape)
print(arr2d.ndim)

20
(2, 10)
2


In [23]:
 # create a vector of a 2D array
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
# or
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
# or
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
# Scaler is a quntity only without any direction
arr = np.array([[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]])
arr

array([[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]])

In [31]:
arr.ndim

20

### 3D Array

In [37]:
arr3d = np.arange(27).reshape(1,1,27) # (depth, row, column)
                                    # (num_of_matrices, row, column)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]]])

## Accessing the elements inside arrays
### 2D

In [39]:
arr2d[1,6]

16

In [40]:
arr2d[1][6]

16

In [47]:
arr3d[0][0][0]

0

In [48]:
arr4d = np.arange(625).reshape(5,5,5,5)
arr4d

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]],


       [[[125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134],
         [135, 1

In [65]:
arr4d[4][3][4][3]

598

In [50]:
arr6d = np.arange(729).reshape(3,3,3,3,3,3)
arr6d

array([[[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8]],

          [[  9,  10,  11],
           [ 12,  13,  14],
           [ 15,  16,  17]],

          [[ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26]]],


         [[[ 27,  28,  29],
           [ 30,  31,  32],
           [ 33,  34,  35]],

          [[ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53]]],


         [[[ 54,  55,  56],
           [ 57,  58,  59],
           [ 60,  61,  62]],

          [[ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71]],

          [[ 72,  73,  74],
           [ 75,  76,  77],
           [ 78,  79,  80]]]],



        [[[[ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]],

          [[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98]],

          [[ 99, 100, 101],
           [102, 1

In [51]:
arr6d[0][0][0][0][2][2]

8

In [52]:
x

array([22, 33, 44, 55])

In [53]:
z = []
for n in x:
    z.append(n*2)
z

[44, 66, 88, 110]

In [54]:
[n**2 for n in x]

[484, 1089, 1936, 3025]

In [73]:
x*2

array([ 44,  66,  88, 110])

In [55]:
x**3

array([ 10648,  35937,  85184, 166375], dtype=int32)

In [56]:
arr2d/10

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [58]:
arr3d*10

array([[[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110,
         120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230,
         240, 250, 260]]])

In [69]:
# shape need to be same to perform above operations.
# mirroring or elementwise operation

In [61]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [63]:
print(x)
print(y)

[22 33 44 55]
[0 1 2 3]


In [66]:
x + y

array([22, 34, 46, 58])

In [70]:
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [73]:
a + b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [74]:
a * b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [77]:
a@b
# linear Algebra Multiplization shown as a.b

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [78]:
c = np.arange(20).reshape(5,4)

In [79]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [81]:
#(5,5)@(5,4)
b@c

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])

In [82]:
#(5,4)@(5,5)
c@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

# Array Slicing

In [83]:
# difference between slicing and indexing

In [84]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
a[2,3] # Simple Indexing is accessing a single element

13

In [93]:
type(a[2,3])

numpy.int32

In [99]:
# However, Slicing needs to provide start and end of the rows and colums to slice out a particular data set from 
# the existing array like below
print(a[2,3]) # Index a[row index, coulmn index]
print(a[2:4,3:5]) # Slicing a [starting row index : ending row index, starting column index : ending coulmn index] 
                  # While last of the index is not included so take care in future.

13
[[13 14]
 [18 19]]


In [100]:
a.ndim

2

In [102]:
a[2:4,3:5].ndim

2

In [103]:
a[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [104]:
a[ :4, :4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [105]:
a[4, :4]

array([20, 21, 22, 23])

# Querrying Array

In [106]:
a > 5 # Mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [108]:
mask = a > 5
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [109]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [110]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
# replacement

a[a > 7] = 100
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [112]:
a[(a % 2 == 0) & (a % 7 == 0)]

array([0])

In [121]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [122]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
a[(a % 2 == 0) & (a % 7 == 0)]

array([ 0, 14])

In [119]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [120]:
a[(a % 2 == 0) & (a % 7 == 0)]

array([ 0, 14, 28])

In [125]:
a[a>7] = 100
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [126]:
a[(a % 2 == 0) & (a % 7 == 0)] 

array([0])

In [128]:
a[(a % 2 == 0) | (a % 7 == 0)] # Boolyan Indexing

array([  0,   2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [129]:
np.where((a % 2 == 0) | (a % 7 == 0), "wow", "ooh")

array([['wow', 'ooh', 'wow', 'ooh', 'wow'],
       ['ooh', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow'],
       ['wow', 'wow', 'wow', 'wow', 'wow']], dtype='<U3')

In [130]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

# Combining Arrays
- Horizontal Stacking 
- Vertical Stacking

In [131]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [132]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [134]:
np.concatenate((a, b))  # by default it takes axis = 0 the rows will increase

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [135]:
np.concatenate((a, b)).shape

(10, 5)

In [136]:
np.concatenate((a, b)).ndim

2

In [137]:
np.concatenate((a, b), axis = 1) # if axis = 1, the columns will increase

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [138]:
np.concatenate((a, b), axis = 1).shape

(5, 10)

In [140]:
np.stack((a, b)) # Stacking is different than the concatenate.

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]]])

In [142]:
np.vstack((a, b)) # vstack = concatenate with axis = 0

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [143]:
np.hstack((a, b)) # hstack = concatenate with axis = 1

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [150]:
np.stack((a, b), axis = 2)

array([[[  0,  25],
        [  1,  26],
        [  2,  27],
        [  3,  28],
        [  4,  29]],

       [[  5,  30],
        [  6,  31],
        [  7,  32],
        [100,  33],
        [100,  34]],

       [[100,  35],
        [100,  36],
        [100,  37],
        [100,  38],
        [100,  39]],

       [[100,  40],
        [100,  41],
        [100,  42],
        [100,  43],
        [100,  44]],

       [[100,  45],
        [100,  46],
        [100,  47],
        [100,  48],
        [100,  49]]])

In [148]:
np.stack((a, b), axis = 2).shape

(5, 5, 2)

# shorthand to repeat a sequence 10 times

In [152]:
a3 = np.array([1, 2] * 10)
a3

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [171]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [172]:
def exp(x):
    return x < 3 or x > 3

np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [173]:
def exp(x):
    return x < 3 or x == 3 or x > 3

np.vectorize(exp)(a)

array([ True,  True,  True,  True,  True])

In [179]:
cri = a >= 3
a[cri]

array([3, 4])

In [180]:
np.sum(cri)

2

In [181]:
a1 = np.arange(1, 10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
a1[3:8] # index 3 included while index 8 is not included

array([4, 5, 6, 7, 8])

In [184]:
a1[3 : 8 : 2] # index 3 included while index 8 is not included and step of 2 is taken

array([4, 6, 8])

In [185]:
a1[ : : 2]

array([1, 3, 5, 7, 9])

In [186]:
a1[ : : -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [187]:
a1[ : : -2]

array([9, 7, 5, 3, 1])

In [188]:
a1[9 : 0 : -1]

array([9, 8, 7, 6, 5, 4, 3, 2])

In [189]:
a1[5 : ]

array([6, 7, 8, 9])

In [190]:
a1[ : 5]

array([1, 2, 3, 4, 5])

In [192]:
m = np.arange(0, 20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [193]:
m[:, 1]

array([ 1,  5,  9, 13, 17])

In [194]:
m[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [202]:
m[3 : 5, :]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [203]:
m[3:5, 1:3]

array([[13, 14],
       [17, 18]])

In [204]:
m[[1, 3, 4], :]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [205]:
a = np.arange(0, 9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [206]:
m = a.reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [207]:
reshapped = m.reshape(9)
reshapped

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
a == reshapped

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [4]:
import numpy as np
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [10]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
 np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
 np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])