# Numpy Vs Python Performance
    - NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
    pure Python counterparts and use significantly less memory.

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2
#CPU times: user 20 ms, sys: 50 ms, total: 70 ms
#Wall time: 72.4 ms

CPU times: total: 15.6 ms
Wall time: 23 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]
# CPU times: user 760 ms, sys: 290 ms, total: 1.05 s
# Wall time: 1.05 s

CPU times: total: 922 ms
Wall time: 927 ms


In [7]:
print(922 / 15.6)
print(927 / 23)

59.1025641025641
40.30434782608695


# 4.1 The NumPy ndarray:

In [8]:
data = np.random.randn(2, 3)
data

array([[ 1.28688645,  0.47151493,  1.08327403],
       [-0.06402961, -1.38539279, -1.6855507 ]])

In [9]:
data * 10

array([[ 12.86886447,   4.71514933,  10.83274033],
       [ -0.64029609, -13.85392789, -16.85550703]])

In [10]:
data + data

array([[ 2.57377289,  0.94302987,  2.16654807],
       [-0.12805922, -2.77078558, -3.37110141]])

# Creating ndarrays

In [11]:
# Method # 01 Using the sequence like object, lists Tupple or existing arrays
data1 = [6, 7.5, 8, 0, 1]
data1


[6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

(5,)
1
5
float64


In [17]:
# Method # 01 nested sequences like equal length lists convert to multi dim arrays
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

(2, 4)
2
8
int32


In [23]:
# Method # 02 Special functions like zeros, ones and empty etc
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
arr4 = np.zeros([3, 6]) # Pass a tupple or list in the function for a particular shape
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
arr5 = np.zeros((3, 6, 9)) # Pass a tupple in the function for a particular shape
arr5

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [31]:
arr6 = np.zeros( (  9,      6,       9)) # Pass a tupple in the function for a particular shape
arr6           # (depth, rows, columns)

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [33]:
arr7 = np.empty([3, 6, 9]) # Pass a tupple in the function for a particular shape
arr7

array([[[ 7.00568840e-312,  7.00568839e-312,  7.00568841e-312,
          7.00568841e-312,  7.00568840e-312,  7.00568840e-312,
          7.00568840e-312,  9.73041595e-072,  9.73041595e-072],
        [ 1.48474364e-076,  9.16221648e-072,  9.73041595e-072,
          9.73041595e-072,  9.73041595e-072,  9.73041595e-072,
          9.73041595e-072,  1.48440497e-076,  9.73041595e-072],
        [ 9.73041595e-072, -2.18352987e-310,  9.73041595e-072,
          1.48474364e-076,  9.73041595e-072,  9.73041595e-072,
          9.73041595e-072,  9.73041595e-072,  9.73041595e-072],
        [ 9.73041595e-072,  9.73041595e-072,  9.73041595e-072,
          9.73041595e-072,  9.73041595e-072,  9.73041595e-072,
          9.73041595e-072,  9.73041595e-072,  9.73041595e-072],
        [ 9.73041595e-072,  9.73041595e-072,  9.73041595e-072,
          9.73041595e-072,  9.73041595e-072,  9.73041595e-072,
          1.39838196e-076,  9.72820509e-072,  9.73041595e-072],
        [ 9.73041595e-072,  9.73041595e-072,  9.73

In [43]:
arr8 = np.arange(15).reshape(3, 5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
np.array(data2).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Type casting the data type

In [48]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_1.dtype

dtype('int32')

In [49]:
float_arr_1 = arr_1.astype(np.float64)
float_arr_1.dtype

dtype('float64')

In [50]:
arr_2 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
arr_2.dtype

dtype('float64')

In [52]:
int_arr_2 = arr_2.astype(np.int32)
int_arr_2

array([1, 2, 3, 4, 5])

In [53]:
int_arr_2.dtype

dtype('int32')

In [57]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [60]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Arithmetic with NumPy Arrays

In [61]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [62]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [63]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [65]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [66]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [67]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [71]:
arr2 = arr

In [72]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

# Basic Indexing and Slicing

In [76]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr[5]

5

In [78]:
arr[5:8]

array([5, 6, 7])

In [80]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [82]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [83]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [85]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [86]:
copy_arr = arr[5:8].copy()
copy_arr

array([64, 64, 64])

In [87]:
copy_arr[:] = 100
copy_arr

array([100, 100, 100])

In [88]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr2d[2]

array([7, 8, 9])

In [92]:
arr2d[1][2]

6

In [93]:
arr2d[1, 2]

6

In [96]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
arr3d[1, 1, 2]

12

In [101]:
arr3d[1: : ]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [107]:
old_values_arr3d_0 = arr3d[0].copy()
old_values_arr3d_0

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [111]:
old_values_arr3d_0

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
arr3d[0] = old_values_arr3d_0
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Indexing with slices

In [114]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [115]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [116]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [126]:
arr2d[2, :2]

array([7, 8])

In [130]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [132]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [137]:
arr2d[2]

array([7, 8, 9])

In [138]:
arr2d[2, :]

array([7, 8, 9])

In [139]:
arr2d[2:, :]

array([[7, 8, 9]])

In [142]:
arr2d[:, :2].shape

(3, 2)

# Boolean Indexing

In [143]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [145]:
data = np.random.randn(7, 4)
data

array([[-0.44183162, -0.29024431,  1.38720824, -0.82643315],
       [ 0.61801371,  1.07225723, -2.00686059,  0.14276579],
       [ 0.62202806, -0.66458347, -1.88729346, -0.37458578],
       [ 0.4751115 ,  0.72693272, -0.84379419, -0.62355635],
       [ 1.31562999,  0.7332637 ,  0.67364495, -0.70561764],
       [-1.04068376,  1.25048846,  1.22169071,  0.47389032],
       [ 0.69207933,  0.45607995,  0.23507771,  1.39917038]])

In [147]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [149]:
data[names == "Bob"]

array([[-0.44183162, -0.29024431,  1.38720824, -0.82643315],
       [ 0.4751115 ,  0.72693272, -0.84379419, -0.62355635]])

In [150]:
data[names == 'Bob', 2:]

array([[ 1.38720824, -0.82643315],
       [-0.84379419, -0.62355635]])

In [151]:
data[names == 'Bob', 3]

array([-0.82643315, -0.62355635])

In [152]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [153]:
data[~(names == 'Bob')]

array([[ 0.61801371,  1.07225723, -2.00686059,  0.14276579],
       [ 0.62202806, -0.66458347, -1.88729346, -0.37458578],
       [ 1.31562999,  0.7332637 ,  0.67364495, -0.70561764],
       [-1.04068376,  1.25048846,  1.22169071,  0.47389032],
       [ 0.69207933,  0.45607995,  0.23507771,  1.39917038]])

# Transposing Arrays and Swapping Axes

In [155]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [156]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [158]:
arr = np.random.randn(6, 3)
arr

array([[-0.55928467,  1.27448738,  0.75080714],
       [-0.25900957,  0.72085857,  1.67522621],
       [-1.45817889,  0.28229797, -0.96891512],
       [ 2.25248184,  0.02855828,  0.13367463],
       [ 1.22948584,  1.2070349 , -0.83942482],
       [ 1.64621655, -0.33380217,  0.17135833]])

In [159]:
np.dot(arr.T, arr)

array([[11.80150979, -0.3123028 ,  0.11016868],
       [-0.3123028 ,  3.79282001,  0.82437529],
       [ 0.11016868,  0.82437529,  5.06075735]])

In [160]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [161]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [162]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [163]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [165]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [167]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [168]:
x = np.random.randn(8)
x

array([ 0.23378665, -0.06098514,  1.02645268,  1.16967679, -1.2882417 ,
       -0.30733296,  0.37593601, -0.34674859])

In [170]:
y = np.random.randn(8)
y

array([-0.9258549 ,  0.56833894,  0.50754803, -0.69744417, -0.58709965,
        1.20724583,  1.247284  ,  1.7370629 ])

In [171]:
np.maximum(x, y)

array([ 0.23378665,  0.56833894,  1.02645268,  1.16967679, -0.58709965,
        1.20724583,  1.247284  ,  1.7370629 ])

In [172]:
arr = np.random.randn(7) * 5
arr

array([ 4.69370816,  0.43024033, -7.07496947,  6.0693506 , -5.94566473,
       -4.86916144,  9.92521872])

In [173]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.69370816,  0.43024033, -0.07496947,  0.0693506 , -0.94566473,
       -0.86916144,  0.92521872])

In [174]:
whole_part

array([ 4.,  0., -7.,  6., -5., -4.,  9.])

In [175]:
arr

array([ 4.69370816,  0.43024033, -7.07496947,  6.0693506 , -5.94566473,
       -4.86916144,  9.92521872])

In [176]:
np.sqrt(arr)

C:\Users\Nadeem\AppData\Local\Temp\ipykernel_23656\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.16649675, 0.65592707,        nan, 2.4636052 ,        nan,
              nan, 3.15043151])

In [177]:
np.sqrt(arr, arr)

C:\Users\Nadeem\AppData\Local\Temp\ipykernel_23656\269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([2.16649675, 0.65592707,        nan, 2.4636052 ,        nan,
              nan, 3.15043151])

In [178]:
arr

array([2.16649675, 0.65592707,        nan, 2.4636052 ,        nan,
              nan, 3.15043151])

# 4.3 Array-Oriented Programming with Arrays

In [180]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [183]:
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray);
plt.colorbar()

NameError: name 'z' is not defined