In [5]:
import numpy as np

In [6]:
array = numpy.array([1, 2, 3, 4, 5])

In [7]:
array

array([1, 2, 3, 4, 5])

In [8]:
print(array)

[1 2 3 4 5]


In [9]:
import numpy as np

In [10]:
array = np.array([2, 3, 4, 5, 6])
print(array)

[2 3 4 5 6]


In [11]:
print(np.__version__)

1.22.4


In [12]:
print(type(array))

<class 'numpy.ndarray'>


In [13]:
tup_array = np.array((1, 3, 5, 7, 9, 11))
print(tup_array)
print(type(tup_array))

[ 1  3  5  7  9 11]
<class 'numpy.ndarray'>


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 04 Create a NumPy ndarray Object

In [15]:
# 2-D Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

array_2D = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2D)

[[1 2 3]
 [4 5 6]]


In [16]:
print(array_2D.ndim)

2


In [20]:
array_4D = np.array([
        [
            [
                [1, 2, 3]
            ]
        ],
        [
            [
                [4, 5, 6]
            ]
        ], 
        [
            [
                [6, 2, 3]
            ]
        ], 
        [
            [
                [4, 8, 6]
            ]
        ]
])

print(array_4D)

print(array_4D.ndim)

[[[[1 2 3]]]


 [[[4 5 6]]]


 [[[6 2 3]]]


 [[[4 8 6]]]]
4


In [21]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
e = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [9, 2, 3],
        [8, 5, 6]
    ],
    [
        [7, 2, 3],
        [6, 5, 6]
    ]
])

print(e.ndim)

3


In [24]:
import numpy as np

array_5D = np.array([1, 2, 3, 4], ndmin = 5)

print(array_5D)
print("\n The dimensions of array_5D are " + str(array_5D.ndim))

[[[[[1 2 3 4]]]]]

 The dimensions of array_5D are 5


In [25]:
array_1D = np.array([1, 2, 3, 4])

print(array_1D[3] - array_1D[2])

1


In [26]:
b = np.array([
    [1, 2, 3, 4],
    [3, 5, 6, 8]
])

print(b)
print(f"\n3rd element of the 2nd row is \"{b[1, 2]}\".")

[[1 2 3 4]
 [3 5 6 8]]

3rd element of the 2nd row is "6".


In [27]:
c = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [7, 8, 9], [10, 11, 12]
    ]
])

print(c)
print(f"\nthird element of the second array of the first array is \"{c[0, 1, 2]}\".")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

third element of the second array of the first array is "6".


In [28]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
