In [1]:
import numpy as np
names = np. array(['Bob' , 'Joe' , 'Boby','Will' ,'Willy' , 'Joe' , 'Joe' ])
data=np.arange(3,10,1)
print(data[names=="Boby"])

[5]


In [ ]:
The data generation functions in numpy.random use a global random seed. To avoid global state, 
you can use numpy.random.RandomState to create a random number generator isolated from others:

In [2]:
import numpy as np
arr = np. arange(6)
arr. reshape((2, -1))

#For Array reshaping one of the passed shape dimensions can be –1, in which case the value 
used for that dimension will be inferred from the data. So in this question it will create 
an array of size 2x3 to arrange all elements of the array.

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
 a) Error
 b) Will create an array of size 3x2
 c) Will create an array of size 2x1
 d) Will create an array of size 2x3

In [ ]:
The opposite operation of reshape from one-dimensional to a higher dimension is typically 
known as flttening or raveling:

In [ ]:
NumPy's library of algorithms written in the C language can operate on this memory without 
any type checking or other overhead. 

In [3]:
import numpy as np
arr = np. arange(10)
print(arr[5:8])

[5 6 7]


In [4]:
# What will be the output of the following code :
arr2d = np. array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1,1:])

[5 6]


In [5]:
# What will be the output of the following code :
import numpy as np
arr = np. arange(10)
arr_slice = arr[5: 8]
arr_slice[:] = 64
print(arr[3:7])

[ 3  4 64 64]


In [8]:
# What will be the output of the following code :
import numpy as np
arr = np.arange(4)
arr.reshape(2,2)
print(arr.ndim)

1


In [9]:
# What will be the output of the following code :
import numpy as np
arr = np. arange(10)
arr[5]=50
print(arr[4:7])

[ 4 50  6]


In [10]:
# What will be the output of the following code :
import numpy as np
arr = np.array([False, True, True, False])
arr.any()

True

In [ ]:
9. Which Numpy Array creation function produce an array of the given shape and dtype with all values 
set to the indicated “fill value”

Numpy.Full


In [ ]:
Which functionality is not present in Numpy

Some functionalities like Time Series manipulation is not present in NumPy. we have to use Pandas for that.

In [11]:
# What will be the output of the following code :
import numpy as np
arr=[-3.2623]
print(np.sqrt(arr))


[nan]


C:\Users\Nadeem\AppData\Local\Temp\ipykernel_20632\4231124872.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr))


In [12]:
# What will be the output of the following code :
import numpy as np
x = np. array([1. , 2. , 3. ])
y = np. array([[6.], [- 1], [8]])
print(" x. dot(y) = \n",x. dot(y))

 x. dot(y) = 
 [28.]


In [65]:
# What will be the output of the following code :
import numpy as np
arr = np.array([11, 2.5, 3.6,-87])
cond = np.array([True, False, True])
result = np.max(np.where(np.abs(arr) > 3, arr,0))
print(result)

# The numpy.where function is a vectorized version of the ternary expression x if condition else y.  
# The numpy.abs computes the absolute value element wise for integer, floating-point, or complex values. 
# numpy.max retrurns the maximum value in the given array. So np.where(np.abs(arr) > 3, arr,0) will return 
# [ 11. 0. 3.6 -87. ] and numpy.max will return the maximum value which is 11.

11.0


In [ ]:
In Python random.seed() function is used to save the state of a random function, so that it 
can generate _________________ on multiple executions of the code
 d) same random numbers

# Seed function is used to save the state of a random function, so that it can generate same 
random numbers on multiple executions of the code.

In [ ]:
Which Numpy function will create a square N x N identity matrix

eye and identity Numpy functions creates a square N × N identity matrix (1s on the diagonal and 0s elsewhere

In [ ]:
In Numpy save and load functions are used for efficiently saving and loading array data on disk. 
Arrays are saved by default in file with extension ___________

.npy

In [32]:
import numpy as np
arr1 = np.array([0, 1, 2, 3])
arr2 = [0, 2, 5]
res = np.in1d(arr1, arr2, invert = True)
print(res)

[False  True False  True]


[0, 2, 5]

In [15]:
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a.shape,a.ndim)

(1, 5) 2


In [16]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.0])
print(arr.astype(np.int32))

[ 3 -1 -2  0 12 10]


In [17]:
import numpy as np
a = np.array([1, 2, 3,4,5])
print(a.shape,a.ndim)

(5,) 1


In [18]:
import numpy as np
arr = np.array([1, 2, 3,4])
print(arr.cumprod(axis=0))

[ 1  2  6 24]


In [19]:
Which statement best describes Numpy's ndarray ?

 c) ndarray, an efficient multidimensional array providing fast array-oriented arith‐ metic operations

SyntaxError: invalid syntax (2480309719.py, line 1)

In [20]:
We can explicitly convert or cast an array from one dtype to another using ndarray’s ________ method:

SyntaxError: invalid syntax (968174737.py, line 1)

In [74]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [23]:
It’s not safe to assume that _______ will return an array of all
zeros.

It’s not safe to assume that np.empty will return an array of all zeros. In some cases, 
it may return uninitialized “garbage” values


SyntaxError: invalid character '’' (U+2019) (2981906432.py, line 1)

In [24]:
import numpy as np
x = [3,45,76,7,34]
y = [1,82,1,88,22]
z=np.maximum(x,y)
print(z)

[ 3 82 76 88 34]


In [ ]:
The most important object defined in NumPy is an N-dimensional array type called?

ndarray

In [25]:
import numpy as np
arr = np.arange(3, 22, 4)
print(arr)

[ 3  7 11 15 19]


In [26]:
arr2d = np. array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1,1:])

[5 6]


In [27]:
arr = np. arange(10)
arr_slice = arr[5: 8].copy()
arr_slice[:] = 64
print(arr[4:7])

[4 5 6]


In [28]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np. array([[5,6], [7,8]])
res=np. hstack((arr1, arr2))
print(res)
# There are some convenience functions, like vstack and hstack, for common kinds of concatenation. 
vstack can be called as vertical stack  whereas hstack can be called as horizontal stack. So the 
answer of this question will be [[0 1 5 6] [2 3 7 8]]

[[0 1 5 6]
 [2 3 7 8]]


In [33]:
data2 = [[1, 2, 3, 4,5,6], [5, 6, 7, 8,9,10]]
arr2 = np.array(data2).reshape(2,2,3)
arr2.ndim

3

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [ ]:
NumPy is often used along with packages like 

d) Matplotlib

In [37]:
import numpy as np
arr = np.array([11, 2, 5,34])
print(arr.cumsum())

[11 13 18 52]


In [39]:
import numpy as np
arr = np.array([11, 2, 5,34])
print(arr.cumsum(axis=0))

[11 13 18 52]


In [38]:
import numpy as np
arr = np.array([11, 2, 5,34])
print(arr.cumsum(axis = 1))
# In multidimensional arrays, accumulation functions like cumsum return an array of the same size, 
but with the partial aggregates computed along the indicated axis according to each lower dimensional slice. 
In our axis is 1 which means on vertical axis but array is a single dimensional array so this code will generate 
error "axis 1 is out of bounds for array of dimension "

AxisError: axis 1 is out of bounds for array of dimension 1

In [40]:
import numpy as np
arr = np.arange(9).reshape((3,3))
print(arr)
print(arr[[0, 1], [0, 2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 5]


In [41]:
import numpy as np
arr = np.arange(3)
arr=arr.repeat(3)
print(arr)
# Two useful tools for repeating or replicating arrays to produce larger arrays are the repeat and 
tile functions. repeat replicates each element in an array some number of times, producing a larger array.

[0 0 0 1 1 1 2 2 2]


In [42]:
import numpy as np
a = np.array([1,2,3])
print (a)

[1 2 3]


In [43]:
import numpy as np
arr = np.array([1, 2, 3,4])
print(arr.cumprod(axis=0))

[ 1  2  6 24]


In [45]:
import numpy as np
arr = np. arange(9)
arr. reshape((2, 4))

ValueError: cannot reshape array of size 9 into shape (2,4)

In [46]:
import numpy as np
arr = np. arange(10)
print(arr[5:8])

[5 6 7]


In [47]:
arr = np.arange(8).reshape((2,4))
arr=arr.T
print(arr[0,1])

4


In [48]:
import numpy as np
arr=[-3.2623]
print(np.sign(arr))
# numpy.sign() function is used to compute the sign of each element. 1 (positive), 0 (zero), or –1 (negative)

[-1.]


In [49]:
import numpy as np
data = np.random.randn(2,3)
print(data)

[[ 0.25685888  2.11079343 -0.04822527]
 [-0.16581439 -1.01122636 -0.90031617]]


In [ ]:
NumPy by itself does not provide

# NumPy by itself does not provide modeling or scientific functionality, having
an understanding of NumPy arrays and array-oriented computing will help you use
tools with array-oriented semantics, like pandas, much more effectively.

In [53]:
import numpy as np
x = [3,45,76,7,34]
y = [1,82,1,88,22]
z=np.maximum(x,y)
print(z)

# In this question universal function numpy.maximum() is used. numpy.maximum computes the element-wise 
maximum of the elements in x and y. So same index element numbers are compared and which ever is higher 
is placed in the result. In the same way all elements of the array are computerd

[ 3 82 76 88 34]


In [55]:
arr = np. array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0][1][2])

6


In [ ]:
In mumpy array np.save and np.load are the two functions for efficiently
saving and loading array data on disk. The Numpy arrays are saved by default in________________



In [56]:
import numpy as np
arr = np.array([11, 2.5, 3.6,-87])
cond = np.array([True, False, True])
result = np.max(np.where(np.abs(arr) > 3, arr,0))
print(result)

11.0


In [ ]:
If we assign a scalar value to a slice, as 
arr[5:8] = 12
This means we have __________ valued in the arr.

In [66]:
import numpy as np
xarr = np. array([1, 2, 3])
yarr = np. array([11, 22, 33])
cond = np. array([True, False, True])
result = np.sum(np.where(cond, xarr, yarr))
print(result)

''' The numpy.where function is a vectorized version of the ternary expression x if condition else y. 
Suppose we had a boolean array and two arrays of values and we wanted to take a value from 1st array 
whenever the corresponding value in condition is True, and otherwise take the value from 2nd array. '''

26


' The numpy.where function is a vectorized version of the ternary expression x if condition else y. \nSuppose we had a boolean array and two arrays of values and we wanted to take a value from 1st array \nwhenever the corresponding value in condition is True, and otherwise take the value from 2nd array. '

In [67]:
"""NumPy is able to save and load data to and from disk either in text or binary format. 
In numpy array np.save and np.load are the two functions for efficiently saving and loading array data 
on disk in an uncompressed raw binary format with file extension .npy:"""

'NumPy is able to save and load data to and from disk either in text or binary format. \nIn numpy array np.save and np.load are the two functions for efficiently saving and loading array data \non disk in an uncompressed raw binary format with file extension .npy:'

In [68]:
import numpy as np
arr = np.array([8, 2, 3,3.5])
print((arr > 2).sum())

"""
In this quiz question boolean values are coerced to 1 (True) and 0 (False) in the preceding methods. 
Thus, sum is often used as a means of counting True values in a boolean array. In this questions the answer will 
be 3
"""

3


In [69]:
"""Which option best describes vectorization ?
The practice of replacing explicit loops with array expressions is commonly referred to as vectorization. 
In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their 
pure Python equivalents, with the biggest impact in any kind of numerical computations. """

'Which option best describes vectorization ?\nThe practice of replacing explicit loops with array expressions is commonly referred to as vectorization. \nIn general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their \npure Python equivalents, with the biggest impact in any kind of numerical computations. '

In [70]:
import numpy as np
arr = [34.5,-76.43,874.34,-343.6,23.3]
print(arr)
r, w = np. modf(arr)
print(r[2])

[34.5, -76.43, 874.34, -343.6, 23.3]
0.34000000000003183


In [71]:
import numpy as np
arr=np. arange(4).reshape((2,2))
arr=arr.ravel('F')
print(arr)

[0 2 1 3]


In [72]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6f', '42i'], dtype=np.string_)
print(numeric_strings.astype(float))

# ValueError

ValueError: could not convert string to float: b'-9.6f'

In [73]:
import numpy as np
arr1 = np.arange(4).reshape(2,2)
arr2 = np. array([[5,6], [7,8]])
res=np.concatenate([arr1, arr2], axis=1)
print(res)

[[0 1 5 6]
 [2 3 7 8]]


In [75]:
"""NumPY stands for?
d) Numerical Python"""

'NumPY stands for?\nd) Numerical Python'

In [76]:
import numpy as np
arr1 = [5, 6, 2, 3, 4]
arr2 = [1, 2, 3]
res = np.setdiff1d(arr1, arr2)
print (res)

[4 5 6]


In [77]:
import numpy as np
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.sum(np.unique(ints)))

10


In [78]:
import numpy as np
arr = np.arange(3)
arr=np.tile(arr,3)
print(arr)

[0 1 2 0 1 2 0 1 2]
